### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#1]
> - cd ~/.drush (This directory should already exist if you've used Drush before.)
> - mkdir commands (This may already exist, if so continue.)
> - wget https://github.com/quicksketch/backdrop-drush/archive/master.zip
> - unzip master.zip -d backdrop

should we `cd commands` and then do the `wget` so that the backdrop directory ends up in the commands directory?

**Comment by quicksketch** [comment]
> should we cd commands and then do the wget so that the backdrop directory ends up in the commands directory?

Yes, that sounds like a better idea, I'll update the readme.

**Comment by quicksketch** [comment]
Thanks fixed in https://github.com/quicksketch/backdrop-drush/commit/21c8394c806f869ef108e14fc6c071d4feca7fd1.
