### ISSUE TITLE
How should third party drush commands signal that they support backdrop?

### ISSUE THREAD

**Issue by kienanstewart** [backdrop-contrib/drush#105]
In my case, I'm looking at the command provision-save provided by the provision projecton on d.org; however, it could really be any third-party command.

In backdrop.drush.inc, the procedure backdrop_drush_command_alter explicitly lists the safe commands, commands that work through a compatibility layer, and rejects everything else.

There currently doesn't seem to be a way to signal to backdrop.drush.inc that a command from a third party falls into one of those categories. This seems fine if the goal of backdrop-drush is to only to support drush core commands, but it would be nice to be able to let other developers support both drupal and backdrop as desired/necessary.

My initial idea is to add a invocation to a drush hook where drush commands (modules? not too sure what to call them) implementing the hook could add commands to the safe / through compatibility layer arrays. 

Consequently, there would probably need to be another hook to let 3rd party commands/modules optionally remap commands.

Thoughts?

**Comment by serundeputy** [comment]
Hello @kienanstewart !

We definitely want to allow modules to declare their own drush commands. Our first attempt at this was here: https://github.com/backdrop-contrib/drush/commit/76e226f5b503bbe5a859696595cd8a6989c1df4b , but that broke compatibility with Drupal sites using drush that had the backdrop drush extension installed, so I had to revert it.

So, short term if you just need a work around you can use that.

Long term we could look more carefully about the what and why that caused drush failures and scope it just to backdrop.

**Comment by quicksketch** [comment]
It looks like another option here is to check the Drush command "path" key, and see if it is a relative or absolute path. Absolute paths come from the global drush install, but relative ones use the local modules. I'll try making a PR to demonstrate.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop-contrib/drush/pull/123. @serundeputy could you give it a shot?

**Comment by serundeputy** [comment]
this works great! and doesn't break D7! #woooooot; merged into `1.x-0.x` will ship with `0.0.7`.
