### ISSUE TITLE
Still having cron error that was supposed to have been fixed last year

### ISSUE THREAD

**Issue by lynna-spidersilk** [backdrop-contrib/drush#106]
I'm still having the problem referred to in the now-closed #8 - not sure if it might be a different cause, though, as that issue is supposed to have been fixed over a year ago. 

The site is using Drush version 8.1.12 and the latest stable versions of both Backdrop and the Drush Backdrop package. 

I had just installed this package, and when trying to run drush cron (from within a Backdrop directory) to see if the installation had been successful, I got:

`Command core-cron needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'cron' could not be executed.                      [error]`

I tried clearing the Drush cache with drush cc, then tried drush cron again and got:

`Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'Drupal\Core\Logger\RfcLogLevel' not found in
phar:///home/[client directory]/bin/drush.phar/commands/core/drupal/environment.inc,
line 334`

Same result if I specifically did drush backdrop-cron. However, I was able to do drush backdrop-core-status successfully, so I guess the Backdrop package did install successfully.

Any ideas why cron is still having problems?

**Comment by serundeputy** [comment]
@lynna-freeform thanks for reporting this issue.

Can you tell me how you have the backdrop drush extension installed?  is it in your home directory; something like `~/.drush/backdrop-extension` or within `drush` itself like `/path/to/drush/extensions/backdorp-extension`?

The cron command is working for myself and others, so there must be some detail about your set up that is different.

fyi; bakcdrop-drush extension requires >= PHP 5.5

Also are you on mac, windows or linux?

**Comment by serundeputy** [comment]
Need more information as I can not reproduce this.

**Comment by quicksketch** [comment]
I just ran into the _exact_ situation. Down to the "first x, then y" errors reported by @lynna-spidersilk. I had just done a fresh OS install, so this is starting entirely from scratch.

I followed the Drush 8 steps from http://docs.drush.org/en/8.x/install/:
```
# Browse to https://github.com/drush-ops/drush/releases and download the drush.phar attached to the latest 8.x release.

# Test your install.
php drush.phar core-status

# Rename to `drush` instead of `php drush.phar`. Destination can be anywhere on $PATH. 
chmod +x drush.phar
sudo mv drush.phar /usr/local/bin/drush

# Optional. Enrich the bash startup file with completion and aliases.
drush init
```

Then I followed the Backdrop drush extension install instructions.

_However_, after doing a `drush cc all`, now everything works just fine:

![image](https://user-images.githubusercontent.com/100206/40737957-12b4d51e-63f7-11e8-8ca9-d914586aa3dd.png)

And after this, I can't seem to make the problem happen any more.

**Comment by serundeputy** [comment]
So, seems specific to having installed drush via a `phar`. I have never done that; so that does identify a difference.

**Comment by klonos** [comment]
I am seeing the same error in [beetbox](https://github.com/beetboxvm/beetbox) installations (uses https://github.com/geerlingguy/ansible-role-drush to install drush):

```
Error: Class &#039;Drupal\Core\Logger\RfcLogLevel&#039; not found in drush_watchdog_severity_levels() (line 334 of /usr/local/share/drush/commands/core/drupal/environment.inc).
```

Actually, I need to run `drush cron` via `sudo`, otherwise I get lots of "rmdir/unlink(/tmp/...) Permission denied ..." warnings. I never had to run `sudo drush` for other commands before.

**Comment by serundeputy** [comment]
@klonos What are the permissions on the beetbox `/tmp` directory?

Drush runs as the cli user (i.e. the user you are logged in as) whereas Backdrop runs as the web user so depending on the file permsission drush may not be able to perform these unlinks.  

Do and `ls -alh /tmp` and paste the results here please.

While your at it you might make sure that the cli user that you are running drush as has full access to the `/tmp` dir.

**Comment by serundeputy** [comment]
As this is specifig to `phar` installs and using `drush cc all` will allow `drush cron` to work I'm closing this as there is no action item for the Drush Backdrop Extension.

As for Beetbox my best guess is permissions, perhaps editing the drush ansible role to be more specific to BB would help, but again no action item for this repo.
