### ISSUE TITLE
Add support for `sql-drop`

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#110]
I thought we had all the sql commands, but `sql-drop` doesn't seem to be working for me. Is it just my set-up again, or is this the case for others too?

**Comment by opi** [comment]
Works fine. `sql-drop` is in the safe commands list https://github.com/backdrop-contrib/drush/blob/1.x-0.x/backdrop.drush.inc#L99

@jenlampton still got the issue ?

**Comment by jenlampton** [comment]
Seems to be working for me today :)
