### ISSUE TITLE
Caches after upgrading Backdrop core

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/drush#112]
When updating Backdrop core with Drush I've had the experience that images/views don't display right until caches are cleared. Is there a way to force a cache clear after a drush upgrade (whether or not there are database updates to run), or is that a bad idea?

**Comment by serundeputy** [comment]
Thanks @laryn !  I don't see any harm in it.
fixed in https://github.com/backdrop-contrib/drush/pull/120

will ship with `0.0.6` or use the latest HEAD of `1.x-0.x`.
