### ISSUE TITLE
CiviCRM drush commands

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/drush#115]
I'm guessing that CiviCRM drush commands could all be added to the safe list since they would be dealing with the CiviCRM database/tables rather than Backdrop specifically. Does that sound right to you?

https://github.com/civicrm/civicrm-backdrop/blob/1.x-master/drush/civicrm.drush.inc

**Comment by serundeputy** [comment]
Thanks @laryn this (https://github.com/laryn/drush/commit/65e4e0031e6fe96120deb30916ff326854f720e7) will work, but what we really need is for `backdropd-drush` to pick up on when modules define their own drush commands: https://github.com/backdrop-contrib/drush/issues/105

So, you can modify your `safe-commands` array as a work around, but I'm hesitant to commit it to the project as we'd have to let all modules that want to define commands (there are plenty of existing modules that do) make PRs against `backdrop-drush` safe commands not very maintainable model.

I'm going to close this issue in favour of #105.

**Comment by serundeputy** [comment]
@laryn #105 has been merged. so you should be able to use drush to run the CiviCRM defined drush commands now!
