### ISSUE TITLE
`drush up` lists module versions in two different formats

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#117]
When running `drush up featherlight/`, the following is shown in part of the output:

```
Current featherlight Version: 1.x-1.0.0
Proposed featherlight Version: 1.0.1
```

The current version is shown as '1.x-1.0.0' while the proposed version doesn't have the '1.x-' at the beginning. I think this should be consistent and either both use the full version string of both use the shortened one...

**Comment by serundeputy** [comment]
indeed.

**Comment by serundeputy** [comment]
Thanks @BWPanda this is fixed in https://github.com/backdrop-contrib/drush/pull/118
