### ISSUE TITLE
[bmake] Add '--no-core' (or similar) argument/functionality

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#133]
As per https://github.com/backdrop-contrib/drush/issues/130#issuecomment-359305446, I'd like `bmake` to support installing modules, themes, etc. into an existing Backdrop installation. This means not installing Backdrop core (either via a command-line argument, or a setting in the make file itself).

From the original post:
> > Support Backdrop multisites (e.g. download modules (and themes, etc.) into /sites/[SITE_NAME]/modules/ and not need to download Backdrop core each time)
> 
> `drush bmake` does not currently do this; I'd like to open a new feature request issue for this one. We can make it happen
> - we'll need to add a `destination` or a `path` option to the `drush dl` command that we can then have `drush bmake` hand off to the new option
> - we'll also have to add some sort of option and syntax in the `[core]` section to tell `bmake` to not download backdrop. maybe something like:
> 
> ```
> [core]
> core = "false"
> ```

**Comment by ghost** [comment]
Made a PR that makes the 'core' part of make files optional: https://github.com/backdrop-contrib/drush/pull/186

If 'core' is left out, or set to `false`, then the 'build path' parameter must be an existing Backdrop installation for the rest of the make file to work.

Could maybe do with some polish, but should be enough to get started.

**Comment by serundeputy** [comment]
Thanks @BWPanda merged into `1.x-1.x` will ship w/ `1.x-1.1.0`
