### ISSUE TITLE
Command `drush dis` disables profiles with modules

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#139]
Today I tried to disable the ckeditor module using drush, and accidentally disabled the `standard` install profile too:

```bash
> drush dis ckeditor
The following projects will be disabled: standard,ckeditor.
    Do you want to disable the projects? (y/n): y

	Success: standard,ckeditor are disabled.

Content permissions have been rebuilt.        
```

Since neither standard (a profile) or ckeditor (a core module) can be enabled using drush, I ended up in a bit of a pickle!

**Comment by serundeputy** [comment]
I think this was addressed in #7 ... closing ... re-open if necessary.
