### ISSUE TITLE
Prevent download suggestion from appearing when it shouldn't

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#140]
Sometimes when you are trying to enable a custom or core module, drush will recommend you use `drush dl` to download it, which will not work. I'd like to find a way to prefent drush from giving our users bad advice.

`
Try downloading jeneration first with the command: drush dl jeneration
`

* Let's check to see if the module requested is in core, and if so, not print the suggestion.
* Let's check to see if the module requested is available via drush dl, and only pring the suggestion if it is.

This is a follow-up to https://github.com/backdrop-contrib/drush/issues/138.

**Comment by serundeputy** [comment]
I just tested this w/ a custom module and `en/dis/pmu` all work fine ... so i'm guessing the work from #7 which spanned several years captured this.

closing.
