### ISSUE TITLE
Command `drush en` doesn't work for sub-modules

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#141]
I retested this today with the latest from #7 and confirm `drush en` still does not work with views_ui module. I get the following errors:

```bash
Error views_ui does not exist in your Backdrop installation.
Try downloading views_ui first with the command: drush dl views_ui
```

that's not good advice :( See #140 about preventing the error message for appearing for sub-modules.

**Comment by serundeputy** [comment]
this was fixed in #7 ... closing.
