### ISSUE TITLE
re-enable `drush sa` for backdrop sites

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#142]
We should be able to get a list of all site aliases from within a backdrop root, as the aliases have nothing to do with backdrop.

**Comment by opi** [comment]
`drush sa` works perfectly here.

My drush aliases file is located at `path/to/docroot/drush/projectname.aliases.drushrc.php`, generated by my BoilerDrop script https://github.com/opi/boilerdrop/blob/master/scripts/create_project#L81-L96

**Comment by opi** [comment]
@jenlampton still have trouble with `drush sa` ?

**Comment by jenlampton** [comment]
no, it works! :)

**Comment by jenlampton** [comment]
I'm getting `This command is not supported yet by Backdrop.` again...  I'm on HEAD for 1.x-1.x.

update: It works if I run it outside a backdrop site. From within a backdrop site, I get the error.

**Comment by opi** [comment]
`drush sa` still works fine with HEAD on 1.x-1.x ... @jenlampton do you have a proper `path/to/docroot/drush/projectname.aliases.drushrc.php` file ?

**Comment by jenlampton** [comment]
@opi yes, I think so. It lists all my site aliases from within a Drupal 7 docroot, so I must. On my computer it lives in `~/.drush/aliases/` though.
