### ISSUE TITLE
`drush up` doesn't always run database updates

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#145]
When updating modules via `drush up`, database updates aren't always run automatically. See https://github.com/backdrop-contrib/drush/issues/144 for the initial discovery about this.

----

PR: https://github.com/backdrop-contrib/drush/pull/158

**Comment by serundeputy** [comment]
Suspected module updates that update hooks were not run on:

* https://github.com/backdrop-contrib/font_awesome/releases/tag/1.x-1.2.5
* https://github.com/backdrop-contrib/simple_mailsystem/releases/tag/1.x-1.0.2

To try to reproduce:

*  install the previous versions of said module(s)
* run `drush up font_aweseome`
  * see if update hooks fire

could be related to multiple update (array) handling, i.e. do they run if you just update the one module vs. running both together like: `drush up font_awesome simple_mailsystem`.

**Comment by ghost** [comment]
Hmm, can't replicate this now... Tried one module with update, then two modules with updates, then 3 modules (two with updates, one without). All work fine.

Will close for now and re-open if it happens again.

**Comment by ghost** [comment]
So this happened again. I updated font_awesome and save_draft at the same time. Database updates were available for both. Font Awesome offered to update first, and appeared to do so, but then when Save Draft also offered to update, the Font Awesome update was listed again, and performing the update made drush hang (nothing happened and I had to Ctrl-c to cancel it). Performing the same updates (neither of which had actually happened) via the UI worked fine.

**Comment by serundeputy** [comment]
@BWPanda thanks for the STR
PR: https://github.com/backdrop-contrib/drush/pull/158

I was able to replicate the problem and this PR solved it for me.  Give it a test if you get a chance thanks!

**Comment by serundeputy** [comment]
Merged #158.
