### ISSUE TITLE
Cache not (always) cleared with updates

### ISSUE THREAD

**Issue by opi** [backdrop-contrib/drush#153]
From https://github.com/backdrop/backdrop-issues/issues/3294#issuecomment-423778432

Relevant quote:
> Drush do not clear cache when there are no updates https://github.com/backdrop-contrib/drush/blob/1.x-0.x/includes/update.inc#L237

**Comment by serundeputy** [comment]
Why would  you  expect/need cache to be cleared on `drush updb` if there are no updates?

**Comment by opi** [comment]
Probably to be consistent with the `update.php` behavior, which clear the cache anyway. See https://github.com/backdrop/backdrop-issues/issues/3294#issuecomment-423744239

**Comment by serundeputy** [comment]
I think this https://github.com/backdrop-contrib/backdrop-drush-extension/pull/158/files corrected this issue.

closing. re-open if i'm incorrect.
