### ISSUE TITLE
`drush uli` Support

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/drush#16]
That's one I use constantly, would love to see it working for us :smile:

**Comment by serundeputy** [comment]
@wesruv have a go at this:
https://github.com/backdrop-contrib/drush/pull/17
https://github.com/backdrop-contrib/drush/pull/17.patch

usage:

```
drush uli --uri=http://example.com
```

If you try it out and give it a RTBC I'll merge it.

thanks,
~Geoff

**Comment by wesruv** [comment]
Hoooooray! It worked!

Your video demo was great, thanks so much for making that!

**Comment by serundeputy** [comment]
Thanks @wesruv RTBC and merged!

glad the vid and `uli` worked!

**Comment by quicksketch** [comment]
Here's a follow-up for this issue: https://github.com/backdrop/backdrop/pull/1308

That would allow login without changing the password, as it worked in D7.
