### ISSUE TITLE
"Use of undefined constant" warnings

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#178]
I'm getting these warnings when running drush commands:

> Use of undefined constant DRUSH_BOOTSTRAP_BACKDROP_CONFIGURATION - assumed 'DRUSH_BOOTSTRAP_BACKDROP_CONFIGURATION' (this will throw an Error in a future version of PHP) backdrop_core.drush.inc:270

>Use of undefined constant DRUSH_BOOTSTRAP_BACKDROP_FULL - assumed 'DRUSH_BOOTSTRAP_BACKDROP_FULL' (this will throw an Error in a future version of PHP) backdrop_core.drush.inc:272

> Use of undefined constant DRUSH_BOOTSTRAP_BACKDROP_LOGIN - assumed 'DRUSH_BOOTSTRAP_BACKDROP_LOGIN' (this will throw an Error in a future version of PHP) backdrop_core.drush.inc:274

I believe this is PHP v7 related, and that the fix is just to put those constants in quotes: https://www.php.net/manual/en/migration72.deprecated.php#migration72.deprecated.unquoted-strings

**Comment by serundeputy** [comment]
Thanks @BWPanda !
Fixed in https://github.com/backdrop-contrib/drush/pull/179
