### ISSUE TITLE
Project name is confusing

### ISSUE THREAD

**Issue by greg-1-anderson** [backdrop-contrib/drush#184]
backdrop-contrib/drush sounds like a fork of drush-ops/drush. The docs call this the "Backdrop Drush Extension", which is much clearer. Perhaps this could become `backdrop-contrib/backdrop-drush-extension`, or even just `backdrop-contrib/drush-extension`?

Github will redirect from the old name to the new name in most instances if you rename the project. Packagist is slightly less forgiving, though.

**Comment by serundeputy** [comment]
I agree @greg-1-anderson .
I don't remember making a deliberate decision to call this `drush`.

I'll work on the name soon. I'm leaning towards `backdrop-drush-extenstion`.

thanks.

**Comment by ghost** [comment]
How 'bout `brush`? 😉

**Comment by ghost** [comment]
Or `backdrush`, which is what [Lando](https://docs.lando.dev/config/backdrop.html#configuration) calls it...

**Comment by AlexShapka** [comment]
> I'll work on the name soon. I'm leaning towards `backdrop-drush-extenstion`.

@serundeputy, `backdrop-drush-extenstion` is an obvious, though a bit long, name. So if possible please consider `brush` instead. As discussed on https://github.com/backdrop-contrib/b/issues/59 I believe `bacon` should go to `Backdrop Console` and `brush` to `Backdrop Drush Extension`, then we would end up having very distinctive and appealing names for both projects.

**Comment by greg-1-anderson** [comment]
I think that `brush` also sounds like a standalone tool, to me at least. It does not matter how long a plugin name is, as you only have to deal with that at install time. I'd recommend you leave this `backdrop-drush-extension`, and pick the name you like for the standalone tool.

**Comment by serundeputy** [comment]
@greg-1-anderson I was avoiding this trying to figure out how it would effect downloads and packagist, but i've finally renamed to `backdrop-drush-extension` and i'll just deal w/ whatever fallout occurs as it comes in.

thanks for all your help! need to give props to `drush-ops/drush` proper and respect the name and that this is and extension.

closing.
