### ISSUE TITLE
Mention Backdrop Console in README as an alternative

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#198]
I only know about [Backdrop Console](https://github.com/backdrop-contrib/b) because @serundeputy pointed it out to me. Maybe there are others who are using Drush but would find `b` more to their liking.

I propose mentioning Backdrop Console in Drush's README as an alternative people might like to consider...

**Comment by ghost** [comment]
And here's a [PR](https://github.com/backdrop-contrib/drush/pull/199).

**Comment by serundeputy** [comment]
@BWPanda you might consider putting a project node for `b` on backdropcms.org too for additional discoverability of `b`.
