### ISSUE TITLE
Remove the 1.x branch in explicitly set input in backdrop_pm.drush.inc 

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/drush#202]
The [line #127](https://github.com/backdrop-contrib/drush/blob/1.x-1.x/commands/pm/backdrop_pm.drush.inc#L127) of the `backdrop_pm.drush.inc` file uses explicitly set 1.x branch as part of a function input:

```
// Get the release info from backdropcms.org.
        $tags = backdrop_pm_get_tags(
          "https://updates.backdropcms.org/release-history/$project/1.x"
        );
```

This won't work for the contributed modules which have 2.x branches, so this should be ideally re-worked to cover 1.x, 2.x, 3.x, and all the future n.x, n+1.x, etc branches.

**Comment by serundeputy** [comment]
@alanmels thank you for raising this issue.

This URL https://updates.backdropcms.org/release-history/$project/1.x Is litterally tracking the release history for modules that claim backdrop `1.x` compatibility as in their `*.info` files.

```bash
backdrop = 1.x
```

So for example `webform` has HEAD on branch `1.x-4.x` but drush only cares about the `1.x` which is indicating the backdrop core compatibility of that module, and drush downloads the correct version of `webform` and other modules.

So, it does not matter if the module goes to a `2.x` version only if/when backdrop goes to a `2.x` version.  When that happens drush will need to detect if the site is a backrop `1.x` or `2.x` site and behave accordingly.

Hope that helps. Closing as no action is required here until backrop `2.x` at which time we'll address this by a drush `2.x` branch.
