### ISSUE TITLE
Offer dev branch for downloading in case if there is no official release

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/drush#203]
Running the `drush dl pwa` command gives:

```
docker@cli:/var/www/docroot/modules$ drush dl pwa

	Error: There is no release located at https://github.com/backdrop-contrib/pwa/releases/download//pwa.zip.
	Try visiting the pwa page directly: https://github.com/backdrop-contrib/pwa

docker@cli:/var/www/docroot/modules$ 
```

Indeed there is no release for the module at https://github.com/backdrop-contrib/pwa/releases. However, there is a development branch 1.x-1.x with a zip-file at https://github.com/backdrop-contrib/pwa/archive/1.x-1.x.zip. So instead of explicitly setting the download address to `https://github.com/backdrop-contrib/$project/releases/download/$latest[0]/$project.zip`, wouldn't be nice if drush offered the development branch for downloading just to cover modules with no official releases?

**Comment by serundeputy** [comment]
@alanmels this is a great idea and will be handled in https://github.com/backdrop-contrib/drush/issues/107

closing as duplicate.
