### ISSUE TITLE
Change README file to better help users with available commands

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/drush#208]
I am one of those "developers" that seldom uses the ```help``` option for commands when using the CLI. I should make better use of this resource, but in the past as I was getting started, this page often just confused me. 

I tend to look at the list of available commands on the README file for drush and forget that there are apparently many more commands supported. 

I think it would be great if we kept a full list of commands in the README file, but at a minimum I am going to suggest a clear adding a clear instruction to users to check the `help` page for more options. 

I will submit a PR to this effect (and it will include adding two more favorites of mine to the README, without being comprehensive). I would be happy for someone to edit this PR or write a new one. Also, I will be happy to revise this PR based upon feedback.

**Comment by stpaultim** [comment]
I just submitted https://github.com/backdrop-contrib/drush/pull/209

But, in looking closer at `drush help` - it would appear that it is still listing many Drupal specific commands that may or may not work with Backdrop. Do I understand that correct?

Should we just try and keep the README up to date?

If so, what other commands should be listed?

**Comment by serundeputy** [comment]
bcex, bcim, bp, dlb, en, dis, pml

**Comment by serundeputy** [comment]
ctl

**Comment by stpaultim** [comment]
@serundeputy - What is ```ctl```. It didn't work for me and ```drush ctl --help``` gave me nothing.

**Comment by stpaultim** [comment]
I've updated the PR with all suggestions except ctl and reorganized them in groupings/order that make sense to me (the best criteria), happy to hear feedback on alternative organization of the list.

**Comment by serundeputy** [comment]
You want drush help ctl

**Comment by serundeputy** [comment]
ctl is only available in >= 1.1.0

**Comment by stpaultim** [comment]
So, I'm working with Lando and the following default recipe:

```
name: demo
recipe: backdrop
config:
  webroot: .
```

How do I tell it to use Drush 1.1.0?

**Comment by serundeputy** [comment]
I think pmu works too

**Comment by serundeputy** [comment]
In the config section add 

backdrush: 1.1.0

**Comment by stpaultim** [comment]
Thanks. I had to destroy and restart lando environment (rebuild did not work). But, I got it working.

**Comment by stpaultim** [comment]
OK, finally finished making a change before you managed to suggest another addition! ;-)
Done for tonight. See updated PR.

**Comment by serundeputy** [comment]
merged: https://github.com/backdrop-contrib/drush/pull/209
thanks @stpaultim !
