### ISSUE TITLE
Drush dlb is not working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/drush#216]
I don't usually use Drush to download Backdrop, but I'm trying today. 

Tried it `drush dlb` alone and using lando `lando drush dlb` and in both cases I got the following error. 

`Missing required argument: module-name.  See `drush help download-backdrop` for information on usage.`

**Comment by serundeputy** [comment]
You need:

```bash
lando drush dlb backdrop
```

**Comment by serundeputy** [comment]
You can also see how to use any command with:

```bash
lando drush help <command>
```

In this case:

```bash
lando drush help dlb
```

**Comment by stpaultim** [comment]
Should the Readme file show this in full - as per my PR?

**Comment by serundeputy** [comment]
Thanks @stpaultim !

I think the README.md change is a good one. Merged: https://github.com/backdrop-contrib/drush/pull/217
