### ISSUE TITLE
Pretty terminal font colors for `drush cset`

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/drush#218]
I have a script that sets up my local when working on Backdrop issues. At the very end of it, I have a series of `drush cset` commands, and the way they are being output on the terminal (white font on black) makes it hard to distinguish which settings have been set to what values:

![Screen Shot 2020-04-10 at 6 51 34 am](https://user-images.githubusercontent.com/2423362/78960975-68fb5000-7af8-11ea-92ec-9e544c9bf0e0.png)

I thought that we should either be wrapping those in single/double quotes or any other character, but then noticed the beautiful light cyan on black text produced by lando, and I thought better something like that instead.

**Comment by klonos** [comment]
...or perhaps we should introduce a `drush_colorize_output($output, $color)` function to be re-used in other places?

**Comment by serundeputy** [comment]
I like it just need some time to pull it down and test it.

**Comment by serundeputy** [comment]
@klonos thanks this is great!

I changed the color from `96m` to `32m` as that is what is used elsewhere in backdrop-drush-extension, which lends itself to the idea of `drush_colorize_output` being a good one, i'd ask you to open a feature request for that.

**Comment by klonos** [comment]
Done: #220

**Comment by klonos** [comment]
![Screen Shot 2020-04-11 at 8 33 42 am](https://user-images.githubusercontent.com/2423362/79036257-2fe1df00-7bcf-11ea-924e-eaace654bd94.png)
