### ISSUE TITLE
Drush 9 is coming

### ISSUE THREAD

**Issue by greg-1-anderson** [backdrop-contrib/drush#23]
Please be aware that Drush 9 will be coming soon.  When it is release, Drush 8 development will continue on the 8.x branch, and master will be Drush 9.

This will be very important for Backdrop folks who want to track the latest and greatest Drush, because the backdrop integration will break in Drush 9.  Not to worry, it will come back better than ever, with more flexibility for Backdrop Drush to override functionality as needed.  For a short while, though, you'll need to track 8.x instead of master.

**Comment by serundeputy** [comment]
@greg-1-anderson thanks; I'll update the README.md!

**Comment by jenlampton** [comment]
:+1:

**Comment by serundeputy** [comment]
Thanks @greg-1-anderson we've updated the README.md to reflect dependency on the `8.x` branch.

~Geoff
