### ISSUE TITLE
Password provided by 'drush si' doesn't work

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/drush#235]
I'm testing drush si to go through the site installation process and it seems to work. However, at the end, it provides with login credentials that don't work. 

I'm using lando and downloaded Backdrop with 'drush dlb backdrop --path=backdrop'

'lando drush si --db-url=mysql://backdrop:backdrop@database/backdrop'

**Comment by serundeputy** [comment]
Thanks Tim; I think this is a dupe of https://github.com/backdrop-contrib/backdrop-drush-extension/issues/151

for now to work around you can use `drush uli` to login to the site.

**Comment by stpaultim** [comment]
Understood. Thanks.
