### ISSUE TITLE
Drush is recommending "Preview" release over latest bug-fix release

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/drush#236]
A user just reported in the forum that upon running `drush up core` drush is recommending  the preview release of 1.18 instead of 1.17.4, which is the expected update version prior to release of 1.18. 

https://forum.backdropcms.org/comment/2533#comment-2533

```
drush up core

Current Backdrop Version:    1.17.3
Proposed Backdrop Version:    1.18.0-preview
```
"I was expecting version 1.17.4
Why is that? I cannot see any way to make it get the security version."

**Comment by serundeputy** [comment]
You can use the `--select` flag to work around this.

https://github.com/backdrop-contrib/backdrop-drush-extension/issues/164#issue-440902089

**Comment by serundeputy** [comment]
dupe
