### ISSUE TITLE
Running drush cc all -y generates errors

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/drush#250]
The following error appears in the watchdog log when running drush cc all -y

```
The function drush_cache_clear_both() (cache.inc:99) called deprecated function drupal_flush_all_caches(). It will be removed in the next major release of Backdrop.
```

 Drush version            :  8.4.9-dev                                                       
 Backdrop Drush           :  1.x-1.x

**Comment by herbdool** [comment]
It looks like not so much an error as a warning. Clearing cache still works I'm guessing? Not sure how easy it is to replace it with the Backdrop version, but until then can ignore the warning.

**Comment by Wylbur** [comment]
This was my issue, had an old version of drush installed.
