### ISSUE TITLE
Drush 8 EOL November 2022

### ISSUE THREAD

**Issue by gitressa** [backdrop-contrib/drush#252]
Thanks for creating and maintaining Drush integration for Backdrop! It works quite well, and I have just created an MR (https://github.com/lando/backdrop/pull/6) which adds `drush site:install` command for the [Getting Started with Backdrop](https://docs.lando.dev/backdrop/getting-started.html#requirements) page.

I just saw that Drush 8 is EOL by November 2022, so I was wondering if the plan is to try extending Drush 8, or perhaps integrate Drush 11?

**Comment by serundeputy** [comment]
Thanks @gitressa 

I think the plan is https://GitHub.com/backdrop-contrib/b

**Comment by gitressa** [comment]
Ah cool, thanks! I quickly tried to add it with the info found at https://github.com/backdrop-contrib/bee/wiki/Using-Bee-with-Lando but am getting this message:

```
~/backdrop$ lando bee
/bin/sh: 1: /usr/local/bin/bee/bee.php: not found
```

I'll do some more testing later.

Perhaps the `backdrop-drush-extension` README could include a link to the replacement Bee?

**Comment by gitressa** [comment]
I now see that is mentioned, but as "Backdrop Console", not "Bee" ... interesting that the same tool has two names :)

Perhaps show both names, like this? (or vice versa)

> ... consider using Bee (aka "Backdrop Console")

**Comment by gitressa** [comment]
It just dawned on me that the Drush 8 EOL date might be extended: https://github.com/drush-ops/drush/issues/5092.

**Comment by stpaultim** [comment]
@gitressa - Bee started out as Backdrop Console and the name was changed to Bee.

**Comment by gitressa** [comment]
Thanks for explaining the reason behind the two names @stpaultim.

On another note, Drush 8 will support Drupal 7 (and Backdrop I assume) until November 2023, @greg-1-anderson just commented: 

> Yes, the documentation is out of date. Drush 8 will continue to be supported for the lifetime of Drupal 7.

https://github.com/drush-ops/drush/issues/5092#issuecomment-1065959827.
