### ISSUE TITLE
Did drush dl stop working for anyone else?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#255]
Until recently, `drush dl` was working great for me on all my backdrop sites. but I'm now seeing an error similar to the below every single time I try it:

```
Error: There is no release located at https://github.com/backdrop-contrib/backup_migrate/releases/download//backup_migrate.zi
```

It appears as though drush is unable to determine the version number it needs to download (see `download//` in the url). I have been fiddling with my computer configuration, but it seems like a strange place to break something. Is this just me?

`bee dl backup_migrate;` works great

**Comment by halofx** [comment]
It isn't just you. Tried to fire a new install up today through Lando - > lando drush dlb backdrop
and was returned:

Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-19 22:22:43 ERROR 404: Not Found.

unzip:  cannot find or open backdrop.zip, backdrop.zip.zip or backdrop.zip.ZIP.
mv: cannot stat 'my_tmp/backdrop': No such file or directory
rm: cannot remove 'backdrop.zip': No such file or directory

        Success:  Project Backdrop CMS downloaded to ./.

**Comment by quicksketch** [comment]
Fixed between https://github.com/backdrop-contrib/backdrop-drush-extension/pull/265 and https://github.com/backdrop-contrib/backdrop-drush-extension/pull/261.

Thanks @tanyabouman for the PR!
