### ISSUE TITLE
Add support for `drush status`

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#26]
Add support for `drush status` so that we can tell if Drush is working or not.

**Comment by serundeputy** [comment]
@jenlampton this adds limited support:

```
geoff@gspmbp backdrop (905/redirect_as_stand_alone) $ backdrop backdrop-core-status
 Backdrop version       :  1.3.x-dev
 Site URI               :  http://backdrop
 Database driver        :  mysql
 Database hostname      :  localhost
 Database username      :  root
 Database name          :  backdrop
 PHP executable         :  /usr/local/bin/php
 PHP configuration      :  /usr/local/etc/php/5.6/php.ini
 PHP OS                 :  Darwin
 Drush script           :  /Users/geoff/brush/drush.php
 Drush version          :  8.1-dev
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :
 Drupal Settings File   :  ./settings.php
```

but, for example it does not show whether or not you are connected to the DB.  It also is not respecting the ailases `st` or `status` you currently must use `backrop-core-status`.

If someone wants to pull down the patch and give this a spin: https://patch-diff.githubusercontent.com/raw/backdrop-contrib/drush/pull/27.patch

thanks,
~Geoff

**Comment by serundeputy** [comment]
#14 re-namespacing allowed this to report Backdrop Bootstrap in st allowed this one access `DRUSH_BOOTSTRAP_BACKDROP_CONFIGURATION`

Ready for community testing.
patch: https://patch-diff.githubusercontent.com/raw/backdrop-contrib/drush/pull/27.patch

**Comment by jackaponte** [comment]
I just tested the patch on my Backdrop 1.3.3 site (Drush 8.0.5); `drush status` works nicely!

RTBC

**Comment by serundeputy** [comment]
Thanks @jackaponte ! merged into `master`.
