### ISSUE TITLE
Can haz release?

### ISSUE THREAD

**Issue by pirog** [backdrop-contrib/drush#29]
Love all things backdrop and this project in particular. 

We are working on adding a "backdrop ready" version to the `drush/drush` docker image however, for our purposes it would be ideal for us to peg to a particular version instead of pulling directly from whatever is at the top of MASTER. 
https://github.com/RobLoach/drush-docker/pull/15

Any issue with pushing a tag here? even if its like 0.0.1-alpha0?

**Comment by jenlampton** [comment]
I think a tag is a good idea. 1.0.0-alpha sounds like a good place to start :)  @serundeputy should we start a META of 1.0.0 release-blockers? or is that pretty much our whole queue at this point?

**Comment by pirog** [comment]
Before you do that it would be great to get this in https://github.com/backdrop-contrib/drush/pull/30 !

**Comment by serundeputy** [comment]
Thanks @jenlampton and @pirog .

I've merged in #30 and I'll cut a release tag now.  I'll go with `0.0.1` as per Semantic Versioning http://semver.org/ this indicates a dev version; It works, has some useful features, but is subject change oft.

thanks,
~Geoff

**Comment by serundeputy** [comment]
Just cut `0.0.1` thanks! closing.  https://github.com/backdrop-contrib/drush/releases

**Comment by pirog** [comment]
yay! awesome!
