### ISSUE TITLE
Let's get `drush si` to work

### ISSUE THREAD

**Issue by pirog** [backdrop-contrib/drush#34]
Probably not as huge of a priority as other things but wanted to get a ticket in. Among other things this would be useful for running Kalabox functional tests like:

``` bash
#
# Do the site install
#
@test "Install our Backdrop site." {

  # Install a Backdrop site
  run $KBOX drush si --db-url=mysql://root@database/backdrop -y
  [ "$status" -eq 0 ]
  [[ $output == *"Installation complete"* ]]

}

#
# `drush dl` should work
#
@test "kbox drush dl should work" {

  # Install a Drupal 7 site
  $KBOX drush dl webform
  [ "$status" -eq 0 ]
  [[ $output != *"Error:  Project webform could not be found."* ]]

}
```

**Comment by serundeputy** [comment]
@Gormartsen this is a port of your `si` for `b` to drush thanks for your work there!
@pirog this `PR` gets `drush si` working.

You can specify all the parameters in one command for a super speedy backdrop install like so:

```
brush si --root=. --site-mail="example@example.com" --locale="en" --db-url="mysql://root:pass@localhost/ems" --db-prefix="" --clean-url=1 --site-name="geoff is the best." --account-pass="elmo" --account-name="root" --account-mail="example+account-mail@example.com"
```

If no `--db-url` string is specified then `si` goes into interactive mode and prompts you for the necessary parameters.

```
    account-mail [admin@example.com]:
    account-name [admin]:
    account-pass [b09fc8637aa8dbf681d5c5606b8f600d]:
    site-name [Backdrop]:
    clean-url [1]:
    Locale [en]:
    site-mail [admin@example.com]: geoff@example.com
    root [.]:
    Database driver [mysql]:
    Database user: root
    Database password: pass
    Database host [localhost]:
    Database port [3306]:
    Database name: ems


    Installing Backdrop. This may take a moment...


    Backdrop installed successfully.

    Username: admin
    password: b09fc8637aa8dbf681d5c5606b8f600d
```

One thing it does not do is create the database for you.  I'm going to open a separate issue for that.

@jenlampton @pirog @Gormartsen are you up for testing?

thanks,
~Geoff

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop-contrib/drush/pull/59/files

* Fixes interactive mode (prompt for `--db-url` data if not provided)
* Creates the DB if it does not exist yet

@pirog up for testing, feedback or RTBC?

**Comment by serundeputy** [comment]
merged.
