### ISSUE TITLE
Add support for drush dl

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#4]

**Comment by quicksketch** [comment]
I merged in @serundeputy's `drush dl` support and then reorganized the project to accommodate for a larger number of commands (since it looks like we'll have to write quite a few of them).

While the current implementation works, it's limited compared to the `drush dl` for Drupal:
- No support for options like `--select`.
- Can't replace existing modules with newer versions.
- Doesn't work with themes (or layouts).

We'll probably need to expand out this support either by adapting the current Drupal drush code to Backdrop (duplicating most of it) or see if it's possible to wrap the core Drush implementation in a Backdrop adjusted version.

**Comment by serundeputy** [comment]
@quicksketch thanks for merging!

> - No support for options like --select.

  I've opened a new issue for this: https://github.com/backdrop-contrib/drush/issues/11

> - Can't replace existing modules with newer versions.

I'm not sure about this one; I put in logic to check if a module is already installed and not overwrite it if is.  If/when I need to update a module I've always used `drush up {some_module}` to do that.  If anyone feels strongly about this please open a separate issue specifying how either it currently works or how you would like it to work and we can figure it out in that issue.

> - Doesn't work with themes (or layouts).

  Filed a new issue for this: https://github.com/backdrop-contrib/drush/issues/12

I'm closing this issue as the other parts are now captured in there own issues.

**Comment by jenlampton** [comment]
I'm unable to get drush dl to work at all on the latest -master from github. Here are my errors:

```
> drush8 dl devel -v
Undefined index: description command.inc:1208                                                                                   [notice]
Initialized Backdrop 1.3.2 root directory at /Users/jlampton/Sites/jeneration/backdrop/www                                      [notice]
Undefined index: description command.inc:1208                                                                                   [notice]
Use of undefined constant DRUPAL_ROOT - assumed 'DRUPAL_ROOT' BackdropBoot.php:428                                              [notice]
Initialized Backdrop site www at .                                                                                              [notice]
Drush command terminated abnormally due to an unrecoverable error.  
```

**Comment by serundeputy** [comment]
Hi @jenlampton 

Here are the environment set up that works for me:
- Install independent copy of drush
- Make an alias to the new copy of drush
- Download the backdrop-contrib drush extension

http://serundrop.staffordtavern.com/using-drush-backdrop-cms

hope that helps.

Maybe if you can point out the differences in your environment we can track down the issue?

thanks,
~Geoff

**Comment by jenlampton** [comment]
At the moment 
- I'm using drush 8 (will update to latest head shortly to test that)
- alias is `drush8` 
- contrib version of drush commands installed in `/.drush/commands`

**Comment by jenlampton** [comment]
THAT WAS IT. I must have not been on a new enough drush 8 version.  Thank you @serundeputy :)  You can now ignore my comment! :)  and YAY DRUSH!!!
