### ISSUE TITLE
Add support for `drush dl backdrop`.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#41]
The current implementation of backdrop drush commands is to swap out the drush core version of the command with the backdrop version once a backdrop install is detected, but in the case of downloading backdrop itself you do not have a backdrop install yet.

We can write a new command say: `drush dl-backdrop` or find someway of detecting the argument `backdrop` in `drush dl backdrop` command.

Probably easier to write the new command.

**Comment by codev0** [comment]
+

**Comment by serundeputy** [comment]
duplicate of: https://github.com/backdrop-contrib/drush/issues/81

closing.
