### ISSUE TITLE
drush si; drush si for drupal creates the database for you.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#45]
Let's get `drush si` for backdrop the same functionality.
- Prompt that you are about to create a DB or Drop tables from one if it already exists.
- Add prompt to remove site config?  `rm -r docroot/files/config_{hash}`?

In other words if a site exists running `drush si` will blow it away and reinstall fresh DB and config, but not codebase.

~Geoff

**Comment by jenlampton** [comment]
This looks like a dupe of https://github.com/backdrop-contrib/drush/issues/34

**Comment by serundeputy** [comment]
No, not a dupe.

#34 gets `si` working for backdrop; this one aims to allow `si` to create the database and install backdrop to it.  Currently with `si` you need to create the DB then use `drush si`.

**Comment by jenlampton** [comment]
Oh, okay.  whoopsie :) ty.

**Comment by serundeputy** [comment]
I've added this functionality into https://github.com/backdrop-contrib/drush/issues/34

closing.
