### ISSUE TITLE
Add support for drush user-password

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#48]
cause, sometimes you forget your password.

**Comment by serundeputy** [comment]
@jenlampton put this through some paces please: https://github.com/backdrop-contrib/drush/pull/58

~Geoff

**Comment by jenlampton** [comment]
woot!  @serundeputy you are fast 👍  testing now...

**Comment by serundeputy** [comment]
@jenlampton great!  Let me know what you find.

**Comment by jenlampton** [comment]
New PR at https://github.com/backdrop-contrib/drush/pull/58 works fabulously!

**Comment by serundeputy** [comment]
Thanks @jenlampton this is merged in `1.x-0.x` and will ship with `0.1.0`
