### ISSUE TITLE
Remove `backdrop-user-password` and `backdrop-user-login` now that the usual suspects are working

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#60]
too many ways to do the same thing = bad UX?

**Comment by serundeputy** [comment]
@jenlampton I'm not sure I understand.

`backdrop-user-password` is the backdrop implementation of `upwd`.  In `backdrop.drush.inc` we implement `backdrop_drush_command_alter` which swaps out the usual drush command implementations for the backdrop versions.  So `upwd` and `user-password` are just aliases for the real backdrop command `backdrop-user-password`.

So removing `backdrop-user-password` and `backdrop-user-login` would remove the `upwd` and `uli` functionality from backdrop drush.

Does that make sense?  Or are you asking for something else?

~Geoff

**Comment by jenlampton** [comment]
Hm, maybe I don't understand how changing drush actually works :)  

Does this mean we have double-commands for other things like `drush backdrop-cc` and `drush backdrop-sql-dump` too? I had thought we were just altering the existing commands and not adding new ones.

**Comment by serundeputy** [comment]
This is from the file: `backdrop.drush.inc` 

Some are safe:

``` php
  // Commands that work with Backdrop with no adjustments.
  $safe_commands = array(
    'cache-get',
    'cache-set',
    'core-exec',
    'help',
    'topic',
    'php-eval',
    'php-script',
    'sql-cli',
    'sql-conf',
    'sql-connect',
    'sql-create',
    'sql-drop',
    'sql-dump',
    'sql-query',
    'sql-sanitize',
  );
```

those do not have duplicates.

Others need to be rewritten and require a new `callback`

``` php
switch ($command['command']) {
    case 'core-cron':
      $backdrop_command = 'backdrop-cron';
      break;
    case 'updatedb':
      $backdrop_command = 'backdrop-updatedb';
      break;
    case 'updatedb-batch-process':
      $backdrop_command = 'backdrop-updatedb-batch-process';
      break;
    case 'updatedb-status':
      $backdrop_command = 'backdrop-updatedb-status';
      break;
    case 'pm-download':
      $backdrop_command = 'backdrop-pm-download';
      break;
    case 'user-login':
      $backdrop_command = 'backdrop-user-login';
      break;
    case 'core-status':
      $backdrop_command = 'backdrop-core-status';
      break;
    case 'pm-update':
      $backdrop_command = 'backdrop-pm-update';
      break;
    case 'pm-enable':
      $backdrop_command = 'backdrop-pm-enable';
      break;
    case 'user-password':
      $backdrop_command = 'backdrop-user-password';
      break;
  }
```

the ones with new callbacks have the "duplicate" commands with familiar aliases.

~Geoff

**Comment by jenlampton** [comment]
Ah, okay.  Thanks for the explanation. Closing this ticket :)
