### ISSUE TITLE
Add support for `drush sa`

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#65]
I know this command isn't directly related to Backdrop, but drush sa doesn't work on my backdrop sites anymore. Super useful if you are hosted on pantheon. Maybe it could be a pass-through command?

**Comment by opi** [comment]
With PR #113, remote aliases works fine, I manage to do a basic `rsync @dev @local`.  

Note that the handy `sql-sync @prod @local` is broken due to https://github.com/backdrop-contrib/drush/issues/114

**Comment by serundeputy** [comment]
thanks @opi !
Merged into `1.x-0.x` will ship with `0.0.6`
