### ISSUE TITLE
Backup files placed in wrong directory

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#66]
When running `drush up` it makes a backup of the module and places it in `[user_home_directory]/.drush/[site_name]-[module_name]-[module_version]`. However Drupal's drush places backups in `[user_home_directory]/drush-backups/[site_name]/[timestamp]/modules/[module_name]`. I don't mind if the end of the path changes slightly, but I'd prefer all backups to be in `drush-backups` rather than`.drush`...

**Comment by serundeputy** [comment]
This seems like a good idea to me. I just hadn't checked/considered it.

We should be able to make this change.

thanks,
~Geoff

**Comment by serundeputy** [comment]
thanks @BWPanda 

Moved the backups to `~/drush-backups/$sitename/$timestamp/$project/module-name-version`.

This is now consistent with drupal drush behavior.
