### ISSUE TITLE
`drush up` cannot handle more than one module at a time

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#67]
When running `drush up captcha devel extlink` it just updates captcha and then exits. No mention of the other two modules and indeed they're not updated when I check the site again... It seems I have to update each module separately.

**Comment by serundeputy** [comment]
Hello @BWPanda you are correct here I can verify that.

It would be great to get this working as you describe (parity with Drupal drush).  I think it is just turning the callback to loop over an array of the specified modules in your example `captcha devel extlink`.

Yes let's get this working here in backdrop drush as well.

thanks!

**Comment by serundeputy** [comment]
Hi @BWPanda this PR allows for you to specify as many modules as you would like as an argument to `drush up {module1 module1 ...}`

I'll have to refactor #68 to cooperate with this PR.

Here is the patch link: https://patch-diff.githubusercontent.com/raw/backdrop-contrib/drush/pull/70.patch

If you can confirm this is working and give it the RTBC tag we can merge it in and cut a release!

thanks,
~Geoff

**Comment by ghost** [comment]
I can confirm this works!

Before patch:

```
$ dup blockify fitvids
This command is not supported yet by Backdrop.                                      [failed]

                Project blockify is up to date :).
```

And after patch:

```
$ dup blockify fitvids
This command is not supported yet by Backdrop.                                      [failed]

                Project blockify is up to date :).


                Project fitvids is up to date :).
```

So apart from the `This command is not supported yet by Backdrop.` notice, I think this is good to go!

**Comment by serundeputy** [comment]
Thanks for testing @BWPanda !

This is merged into `1.x-0.x` and `1.x-0.0.x` and will ship with `0.0.3`.

It is available now by using the HEAD of `1.x-0.0.x`.  It is also on HEAD of `1.x-0.x`, but that one is a bit broken as the `en` command on that branch breaks drupal usage.

thanks!
~Geoff
