### ISSUE TITLE
Allow training slashes in module names

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#68]
When updating a bunch of modules, I'm usually in the `modules` directory and I type the first part of the module's name then use tab-completion to fill in the rest. This makes things much quicker, however it also means that module name's are output with a trailing slash: `drush up devel/`

One thing that's always annoyed me about Drupal's drush was that you can't just leave the training slash there. It says "Specified project not found". Backdrop's drush does the same. But I think there's an opportunity here to make Backdrop better by allowing a training slash, and then just stripping it when searching for the module on Github (or wherever it searches for them).

Thoughts?

**Comment by serundeputy** [comment]
@BWPanda Thanks for all your great input!

It sounds like a good idea to me.  We should be able to strip out the trailing slash.

**Comment by serundeputy** [comment]
@BWPanda here is a patch that allows for trailing slashes in the machine name when using `drush up {some_module}/`

Up for testing?
Patch link: https://patch-diff.githubusercontent.com/raw/backdrop-contrib/drush/pull/69.patch

If we can get this RTBC we can merge and cut a release!

**Comment by ghost** [comment]
This seems to need re-doing as it can't find the right file to patch...

**Comment by serundeputy** [comment]
> I'll have to refactor #68 to cooperate with this PR.

Yes.  #67 changes this one.  So, I'll merge in #67 and then re-roll this one (#68).  Thanks for testing!

**Comment by serundeputy** [comment]
@BWPanda I've refactored this and merged into `1.x-0.x`.  use that branch to get this functionality.
