### ISSUE TITLE
Support `drush pm-lost` command

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drush#73]
Not an official Drupal Drush command (or even a contrib module), but a very handy Drush command I use regularly. Wondering if it can be easily incorporated into Backdrop's Drush...?

https://gist.github.com/kalabro/3187485

----

PR @BWPanda https://github.com/backdrop-contrib/drush/pull/152

**Comment by ghost** [comment]
I guess I should probably explain what it does... :blush: 

`drush pm-lost` lists any modules in the filesystem that aren't installed on the website (e.g. if you uninstall a module but then forget to actually remove it from the `modules` directory). Helps remove clutter basically.

**Comment by ghost** [comment]
I re-wrote @kalabro's Drush command to make it Backdrop-friendly. It's available here and working nicely from my testing: https://gist.github.com/BWPanda/c82f09d8490b5a04a8b5468e001df642

**Comment by serundeputy** [comment]
@BWPanda if you want to file it as a PR i'm not opposed to putting it into `backdrop-contrib/drush`

**Comment by ghost** [comment]
@serundeputy If there's interest from others, then I'd be happy to do that. Otherwise for now I'm fine with it being separate (I've always used the Drupal version as such).

**Comment by ghost** [comment]
So I've made a PR to add this in to Drush. I've changed it somewhat from the version I posted before, hopefully for the better ;-)

Give it a try and let me know what you think.

**Comment by ghost** [comment]
@serundeputy The PR [was closed](https://github.com/backdrop-contrib/drush/pull/152#event-2463411030), but I'm not sure why... Do I need to do something to it, is the feature request denied (in which case this issue should be closed too), or was it a mistake?

**Comment by serundeputy** [comment]
@BWPanda sorry didn't clarify when i was cleaning up the queue, for posterity here are my thoughts.

Ultimately I just don't find that definition of `lost` very useful. So from my perspective that form of the lost command should live in drush contrib as an extension.

I think a better course of action would be to enhance the `pml` command to be able to filter by `core`, `enabled`, and `disabled`.

For now a working solt'n is `drush pml |grep disabled`
