### ISSUE TITLE
Add support for backdrop-config-import (bcim)

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#75]
This command will complete the workflow for managing your configuration either in version control or from the command line.

It copies files from stage => active and runs the necessary updates

**Comment by serundeputy** [comment]
`bcim` merged into `1.x-0.x` and released in `0.0.4`
https://github.com/backdrop-contrib/drush/pull/88

**Comment by jenlampton** [comment]
Does this command copy files from stage => active? (and make the necessary schema changes that accompany the config changes?)
edit: yes, yes it does :D

**Comment by ghost** [comment]
@serundeputy @jenlampton I don't see any code for running updates... Am I missing something?

**Comment by jenlampton** [comment]
~running updates... you mean like `drush updb`?~
edit: I just read my previous comment...  and edited it so I wouldn't be confused next time :)

**Comment by ghost** [comment]
I'm sorry, I still don't see where there'd be any schema changes being made...

All I see is it gets the appropriate directories, gets a diff of the changes, shows the diff in a table, confirms to make the change, then copies the files...

What am I missing?

**Comment by ghost** [comment]
I think I worked it out... `config_sync_file()` in https://github.com/backdrop/backdrop/blob/1.x/core/modules/config/config.sync.inc#L203 includes invocations of `config_create/update/delete` hooks. I don't think Drush does this, so if a module implements `hook_config_create()`, it won't get called.

**Comment by serundeputy** [comment]
seems like it will have to play a part, but i have to look at that more carefully before deciding what and how to implement it.

thanks for digging that up
