### ISSUE TITLE
`drush help` does not work inside of Backdrop installations.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/drush#97]
If you are just in your file system like in `/home` you can you use `drush help` for backdrop commands:

```bash
geoff@yep ~ $ drush help bcex
Export a Backdrop site configuration.

Examples:
 drush bcex                                Exports the configuration for the current site to the staging config directory.

Options:
 --destination                             Provide a path/to/directory where you wish to export the config.

Aliases: bcex
```

but if you are in a backdrop site directory it does not work:

```bash
geoff@yep backdrop (1.x) $ drush help bcex
This command is not supported yet by Backdrop.
```

The `help` command is defined as a `$safe_command` in `backdrop.drush.inc` meaning it is a command that works out of the box using the code from drush proper project (no additional code from backdrop-drush-extension), but it does not seem to work when in a backdrop installation.

----

PR: https://github.com/backdrop-contrib/drush/pull/159

**Comment by serundeputy** [comment]
the reason this does not work is that `drush help {command}` passes off to `helpsingle` ... the solt'n is to allow `helpsingle` as a `safe_command` in backdrop drush.

PR: https://github.com/backdrop-contrib/drush/pull/159 

while this allows `drush help dlb` to be more useful to Backdrop users, it is still does not work great for all commands, i.e. for commands that are backdrop specific it works great `dlb`, `bcim, `bcex` etc, but for commands like `cc` it currently returns the drupal help.

`drush help bcim`:

```bash
└─ $ ∴ lando drush help bcex
Export a Backdrop site configuration.

Examples:
 drush bcex                                Exports the configuration for the current site to the staging config directory.

Options:
 --destination                             Provide a path/to/directory where you wish to export the config.

Aliases: bcex

```

`drush help cc`:

```
└─ $ ∴ lando drush help cc
Clear a specific cache, or all drupal caches.

Arguments:
 type                                      The particular cache to clear. Omit this argument to choose from available caches.

Aliases: cc

```

I'm going to merge the PR as is as I believe it is an improvement and iterate on this in future releases.

**Comment by opi** [comment]
Tested this morning on 0.1.0 release, and `drush help bcex` works outside **and** inside of Backdrop installations.

**Comment by opi** [comment]
and https://github.com/backdrop-contrib/drush/pull/159 is merged, so closing this issue.
